# Generated by Django 6.0.1 on 2026-01-29 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(null=True)),
                ('unit_price', models.IntegerField(null=True)),
                ('qty', models.IntegerField(null=True)),
                ('total_amount', models.IntegerField(null=True)),
                ('stock', models.CharField(choices=[('Available', 'Available'), ('Out_of_stock', 'Out_of_stock')], max_length=200, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.categorymodel')),
            ],
        ),
    ]
