# Generated by Django 6.0.1 on 2026-01-30 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentmodel',
            old_name='total_free',
            new_name='food_fee',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='Roll',
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='image',
            field=models.ImageField(null=True, upload_to='imag/'),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='total_fee',
            field=models.DecimalField(decimal_places=2, max_digits=50, null=True),
        ),
    ]
