# Generated by Django 6.0.1 on 2026-01-30 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_total_free_studentmodel_food_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='food_fee',
            field=models.DecimalField(decimal_places=10, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='food_per',
            field=models.DecimalField(decimal_places=10, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='total_fee',
            field=models.DecimalField(decimal_places=10, max_digits=50, null=True),
        ),
    ]
