# Generated by Django 6.0.1 on 2026-01-31 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='roll',
            new_name='role',
        ),
    ]
